// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Rcpp_hc
double Rcpp_hc(NumericMatrix X, int K, string methode);
RcppExport SEXP _clustering_Rcpp_hc(SEXP XSEXP, SEXP KSEXP, SEXP methodeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< string >::type methode(methodeSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_hc(X, K, methode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_clustering_Rcpp_hc", (DL_FUNC) &_clustering_Rcpp_hc, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_clustering(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
