# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_hc <- function(X, K, methode) {
    .Call('_clustering_Rcpp_hc', PACKAGE = 'clustering', X, K, methode)
}

